# Generated by Django 4.2.1 on 2023-05-25 13:53

import crm_app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('nip', models.IntegerField(help_text='wpisz NIP bez myślników', max_length=10, unique=True, validators=[crm_app.validators.validate_nip_number])),
                ('address', models.CharField(max_length=128)),
                ('url_site', models.URLField(max_length=64)),
                ('score', models.IntegerField(help_text='wartość musi być z przedziału 0-100', max_length=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('income', models.IntegerField(max_length=10)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('updated', models.DateField()),
            ],
        ),
    ]
