# Generated by Django 4.2.1 on 2023-05-25 13:59

import crm_app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_rename_companies_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='income',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='nip',
            field=models.IntegerField(help_text='wpisz NIP bez myślników', unique=True, validators=[crm_app.validators.validate_nip_number]),
        ),
        migrations.AlterField(
            model_name='company',
            name='score',
            field=models.SmallIntegerField(help_text='wartość musi być z przedziału 0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
