# Generated by Django 4.2.1 on 2023-05-25 15:21

import crm_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_alter_company_income_alter_company_nip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='nip',
            field=models.CharField(help_text='wpisz NIP bez myślników', unique=True, validators=[crm_app.validators.validate_nip_number]),
        ),
    ]
