# Generated by Django 4.2.1 on 2023-05-30 15:07

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0012_legalform_alter_branch_name_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='application',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='kwh_amount',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
