# Generated by Django 4.2.1 on 2023-06-01 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0014_alter_branch_name_alter_legalform_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='legal_form',
            field=models.ForeignKey(default='10', on_delete=django.db.models.deletion.CASCADE, to='crm_app.legalform'),
            preserve_default=False,
        ),
    ]
