# Generated by Django 4.2.1 on 2023-06-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0015_company_legal_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalform',
            name='name',
            field=models.CharField(choices=[('spółka akcyjna', 'spółka akcyjna'), ('spółka z o.o.', 'spółka z o.o.'), ('spółka komandytowa', 'spółka komandytowa'), ('spółka jawna', 'spółka jawna'), ('spółka cywilna', 'spółka cywilna'), ('1-os. DG', '1-os. DG'), ('spółdzielnia', 'spółdzielnia'), ('spółka komunalna', 'spółka komunalna'), ('wspólnota', 'wspólnota'), ('inna', 'inna')], max_length=32),
        ),
    ]
